config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'page#home'
  get 'about',to:'page#about'
  resources :articles
  get 'signup',to:'users#new'   
  resources :users,except: [:new]  
  get 'login',to: 'sessions#new'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'  
  resources :categories,except:[:destroy]
end
   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories,through: :article_categories
    validates :title,presence: true,length:{minimum: 6,maximum: 100}
    validates :description,presence: true,length:{minimum: 10,maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories 
    has_many :articles ,through: :article_categories
    validates :name,presence: true,uniqueness:{case_sensitive:true},length:{minimum: 4,maximum:8}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email=email.downcase}
    has_many :articles ,dependent: :destroy
    validates :name,presence: true,uniqueness: {case_sensitive:false},length:{minimum: 3,maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,presence: true,uniqueness: {case_sensitive:false},length:{maximum: 105},format:{with: VALID_EMAIL_REGEX}
    has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method:current_user,:logged_in?
    def  current_user
        @current_user ||=User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user   
    end

    def require_user
        if !logged_in?
            flash[:alert]="You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only:[:show,:edit,:update,:destroy]
    before_action :require_user,except:[:show,:index]
    before_action :require_same_user,only:[:edit,:update,:destroy]

    def show 
    end

    def index
        @articles=Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article=Article.new
    end

    def edit        
    end

    def create
        @article=Article.new(article_params)
        @article.user=current_user
        @article.save
        if @article.save
        # render plain: @article.inspect
        # if @article.save
            puts "hello in save if block"
            flash[:notice]="Article was created Successfully."
            redirect_to @article 
        else 
            puts "hello in else block"    
            render 'new' ,status: :unprocessable_entity
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice]="Article was updated Successfully"
            redirect_to @article
        else
            render 'edit',status: :unprocessable_entity
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end 

    private

    def set_article
        @article=Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title,:description,:category_ids)
    end

    def require_same_user
        if current_user!=@article.user && !current_user.admin?
            flash[:alert]="You can only edit or delete your own Article."
            redirect_to @article
        end
    end
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:show,:index]

    def new
        @category=Category.new
    end

    def create
        @category=Category.new(category_params)
        if @category.save
            flash[:notice]="Category was successfully created."
            redirect_to @category
        else
            render 'new' ,status: :unprocessable_entity
        end
    end

    def show
        @category=Category.find(params[:id])
        @articles=@category.articles.paginate(page: params[:page],per_page: 5)
    end

    def index
        @categories=Category.paginate(page: params[:page], per_page: 4)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if!(logged_in? && current_user.admin?)
            flash[:alert]="Only Admins can perform this"
            redirect_to categories_path
        end
    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController

    def new
    end

    def create
        user=User.find_by(email:params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[:notice]="Logged In Successfully"
            redirect_to user 
        else
            flash.now[:alert]="There was something wrong with Login Details"
            render 'new',status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id]=nil
        flash[:notice]="Logged Out"
        redirect_to root_path
    end
end    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user,only:[:show,:update,:edit,:destroy]
    before_action :require_user,only:[:edit,:update]
    before_action :require_same_user,only:[:edit,:update,:destroy]


    def show
        @articles=@user.articles.paginate(page: params[:page], per_page: 3)
    end

    def index
        @users= User.paginate(page: params[:page], per_page: 3)
    end


    def new
        @user=User.new
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.update(user_params)
            flash[:notice]="Your account information was successfully updated."
            redirect_to user_path
        else
            render 'edit',status: :unprocessable_entity
        end      
    end

    def create
        @user=User.new(user_params)
        if @user.save
            session[:user_id]=@user.id
            flash[:notice]="Welcome to the alpha blog,#{@user.name} has successfully signed up."
            redirect_to articles_path
        else
            render 'new',status: :unprocessable_entity
        end
    end

    def destroy
        @user.destroy
        session[:user_id]=nil if @user==current_user
        flash[:notice]="Account and all associated article successfully deleted."
        redirect_to articles_path
    end
   
    private

    def user_params
        params.require(:user).permit(:name,:email,:password)
    end

    def set_user
        @user=User.find(params[:id])
    end

    def require_same_user
        if @user!=current_user && !current_user.admin?
            flash[:alert]="You can only edit or delete your account"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user,options=80)
        email_addr=user.email
        hash=Digest::MD5.hexdigest(email_addr)
        gravatar_url="https://www.gravatar.com/avatar/#{hash}?s=#{options}"
        image_tag(gravatar_url,alt:user.name,class:"rounded shadow mx-auto my-4 d-block")
    end

end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/_article.html.erb
<div class="container mb-4">
    <% @articles.each do |article|%>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow bg-white mb5 p3 rounded">
                <div class="font-italic card-header ">
                    <%if article.user%>
                        <%=link_to article.user.name,user_path(article.user) %>
                    <%end%>
                     <%if article.categories.any?%>
                        <div class="mt-2"><%=render article.categories%></div>
                    <%end%>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title,article_path(article.id),class:"text-success" %></h5>
                    <p class="card-text"><%= truncate(article.description,length:100)%></p>
                    <%= link_to 'View',article_path(article.id),class:"btn btn-outline-success"%>
                    <%if logged_in? && (article.user==current_user ||current_user.admin?)%>
                        <%= link_to 'Edit',edit_article_path(article.id),class:"btn btn-outline-info"%>
                        <%= link_to 'Delete', article_path(article.id),class:"btn btn-outline-danger",data: { turbo_method: :delete,turbo_confirm: 'Are you sure?' }%>
                    <%end%>
                </div>
                <div class="card-footer text-muted">
                    <small>Created about <%=time_ago_in_words(article.created_at)%> ago,edited about <%=time_ago_in_words(article.updated_at)%> ago</small>
                </div>
                </div> 
            </div>
        </div>
    <%end%>
</div>

app/views/articles/_forms.html.erb
<div class="container">
    <div class="row justify-content-center ">
        <div class="col-10">
            <%= render 'shared/errors',obj: @article%>
            <%= form_with(model: @article,class:"shadow bg-info p-3 mb-3", local: true) do |f| %>
                <div class="form-group row mx-4 my-3">
                    <%= f.label :title,class:"col-2 col-form-label px-4 text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title,class:"form-control mt-4 mx-auto px-4 shadow rounded",placeholder:"Title of article"%>
                    </div>
                </div>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :description,class:"col-2 col-form-label px-4 text-light"%>
                    <div class="col-10">
                        <%= f.text_area :description,rows:10,class:"form-control mt-4 shadow rounded",placeholder:"Description of article"%>
                    </div>
                </div>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :category,class:"col-2 col-form-label px-4 text-light"%>
                    <div class="col-10">
                        <%= f.collection_select(:category_ids,Category.all,:id,:name,{prompt:"Make you selection from list below(can be empty)"},{multiple: true,size: 3,class:"custom-select shadow rounded"})%>
                    </div>
                </div>

                <div class="justify-content-center form-group row">
                    <div class="btn btn-outline-light btn-lg"> 
                        <%= f.submit%>
                    </div>
                </div> 
            <%end%>
        </div>
        <div class="row col-10 justify-content-center ">
            <%= link_to '[Cancel and Return to Article List Page]',articles_path,class:"text-info"%>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Articles</h1>
<%= render 'forms'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles Listing Page</h1>
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>
<%=render 'article'%>
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>
<%= link_to 'Create Article',new_article_path %> 

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new Article</h1>
<%= render 'forms'%>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%=@article.title%></h1>
<div class="container">
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow bg-white mb5 p3 rounded">
                <div class="font-italic card-header ">
                    <%=@article.user.name if @article.user%>
                    <%=link_to gravatar_for(@article.user),user_path(@article.user)%>
                    <%if @article.categories.any?%>
                        <div class="mt-2"><%=render @article.categories%></div>
                    <%end%>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to @article.title,article_path(@article.id),class:"text-success" %></h5>
                    <div class="card-text text-left"><%= simple_format(@article.description)%></div>
                    <%if logged_in? && (@article.user==current_user || current_user.admin?)%>
                        <%= link_to 'Edit',edit_article_path(@article.id),class:"btn btn-outline-info"%>
                        <%= link_to 'Delete', article_path(@article.id),class:"btn btn-outline-danger" ,method: "delete", data: { confirm: 'Are you sure?' }%>
                    <%end%>
                </div>
                <div class="card-footer text-muted">
                    <small>Created about <%=time_ago_in_words(@article.created_at)%> ago,edited about <%=time_ago_in_words(@article.updated_at)%> ago</small>
                </div>
                </div> 
            </div>
        </div>
</div>
<p><%= link_to 'Create Article',new_article_path %></p>

app/views/categories/_category.html.erb
<%=link_to category.name,category_path(category),class:"badge badge-pill badge-info mr-1"%>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="apple_pagination">
    <%= will_paginate @categories,:container=>false %>
</div>
<div class="container mb-4">
    <% @categories.each do |category|%>
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center shadow bg-white mb5 p3 rounded">
                <div class="card-body">
                    <h5 class="card-title"><%= link_to category.name,category_path(category),class:"text-success" %></h5>
                    <p class="card-text "><%= pluralize(category.articles.count,"article") %></p>
                </div>
                <div class="card-footer text-muted">
                    <small>Created about <%=time_ago_in_words(category.created_at)%> ago,edited about <%=time_ago_in_words(category.updated_at)%> ago</small>
                </div>
                </div> 
            </div>
        </div>
    <%end%>
</div>
<div class="apple_pagination">
    <%= will_paginate @categories,:container=>false %>
</div>

app/views/categories/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a New Category</h1>
    <div class="container">
    <div class="row justify-content-center ">
        <div class="col-10">  
            <%= render 'shared/errors',obj: @category%>
            <%= form_with(model: @category,class:"shadow bg-info p-3 mb-3  ", local: true) do |f| %>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :name,"Category name",class:"col-2 col-form-label px-4 text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name,class:"form-control shadow rounded",placeholder:"Enter Name"%>
                    </div>
                </div>
                <div class="justify-content-center form-group row">
                    <div class="btn btn-outline-light btn-lg"> 
                        <%= f.submit%>
                    </div>
                </div> 
            <%end%>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%=@category.name%></h1>

 <%if logged_in? && current_user.admin?%>
        <%=link_to "Edit Category Name",edit_category_path(@category),class:"btn btn-outline-info"%>
    <%end%>
</div>
<h3 class="text-center mt-4"><%=@user.name%> Articles</h3> 
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>
<%= render'articles/article'%>
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%=link_to "Google","https://www.google.com",class:"text-white"  %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<%flash.each do|name,msg|%>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <p><%= link_to "ALPHA BLOG",root_path,class:"navbar-brand" ,id:"logo"%></p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
                <%= link_to "Home",articles_path,class:"nav-link active"%>
                <li class="nav-item">
                <%=link_to 'Bloggers',users_path,class:"nav-link"%>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Articles
                    </a>
                    <ul class="dropdown-menu">
                    <%if logged_in?%>
                        <li><%= link_to 'Create Article',new_article_path,class:"dropdown-item"%>|</li>
                    <%end%>  
                        <li><%= link_to 'Articles List',articles_path,class:"dropdown-item" %>|</li>
                    </ul>
                </li>

                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu">
                    <%if logged_in? && current_user.admin?%>
                        <li><%= link_to 'Create New Category',new_category_path,class:"dropdown-item"%>|</li>
                    <%end%>  
                        <li><%= link_to 'View Categories',categories_path,class:"dropdown-item" %>|</li>
                    </ul>
                </li>
                <%if logged_in?%>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%if current_user.admin?%>
                                <%="(Admin)"%>
                            <%end%>
                            <%=current_user.name%>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'View Profile',user_path(current_user),class:"dropdown-item"%>|</li>
                            <li><%= link_to 'Edit Profile',edit_user_path(current_user),class:"dropdown-item" %>|</li>
                            <li><%= link_to 'Delete Profile',user_path(current_user),class:"dropdown-item text-danger",data: { turbo_method: :delete,turbo_confirm: 'Are you sure?' }%>|</li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'Logout',logout_path,class:"nav-link",data: { turbo_method: :delete}%>
                    </li>
                <%else%>
                    <li class="nav-item">
                        <%= link_to 'Log In',login_path,class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'Sign up',signup_path,class:"nav-link"%>
                    </li>
                <%end%>
            </li>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/page/about.html.erb
<h1>This is about Page</h1>
<%= link_to 'Article List Page',articles_path %>|
<%= link_to 'Home Page',root_path %>

app/views/page/home.html.erb
<div class="container" id="home-container">
  <div class="mt-6 pt-6 bg-secondary text-white text-center">
      <h1>Alpha Blog</h1> 
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p> 
      <%= link_to 'Sign up!',signup_path,class:'btn btn-success btn-lg'%>
  </div>
</div>
<%= link_to 'Article List Page',articles_path %>|
<%= link_to 'About Page',about_path %>
 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following Errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <%=puts "In new.html"%>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <%=puts msg%>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center ">
        <div class="col-10">  
            <%= render 'shared/errors',obj: @user%>
            <%= form_with(model: @user,class:"shadow bg-info p-3 mb-3  ", local: true) do |f| %>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :name,class:"col-2 col-form-label px-4 text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name,class:"form-control shadow rounded",placeholder:"Enter Username"%>
                    </div>
                </div>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :email,class:"col-2 col-form-label px-4 text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email,class:"form-control shadow rounded",placeholder:"Enter Email Address"%>
                    </div>
                </div>

                <div class="form-group row mx-4 my-3">
                    <%= f.label :password,class:"col-2 col-form-label px-4 text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password ,class:"form-control shadow rounded",placeholder:"Choose a Password"%>
                    </div>
                </div>

                <div class="justify-content-center form-group row">
                    <div class="btn btn-outline-light btn-lg"> 
                        <%= f.submit%>
                    </div>
                </div> 
            <%end%>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit your Profile</h1>
    <%= render 'form'%>
</div>

app/views/users/index.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Alpha Bloggers</h1>
    <div class="apple_pagination">
        <%= will_paginate @users,:container=>false %>
    </div>
    <div class="container mb-4">
        <% @users.each do |user|%>
            <div class="row justify-content-md-center">
                <div class="col-8 mt-4">
                    <div class="card text-center shadow bg-white mb5 p3 rounded">
                        <div class="font-italic card-header ">
                            <%=link_to user.name,user_path(user) %>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to gravatar_for(user,150),user %></h5>
                            <p class="card-text "><%= pluralize(user.articles.count,"article") %><br>
                            <%= link_to 'View Profile',user_path(user),class:"btn btn-outline-success"%>
                            <%if logged_in?%> 
                                <%if user==current_user%>
                                    <%= link_to 'Edit Profile',edit_user_path(user),class:"btn btn-outline-info"%>
                                <%end%>
                                <%if current_user.admin?%>
                                    <%=link_to "Delete user",user_path(user),class:"btn btn-outline-danger",data: { turbo_method: :delete,turbo_confirm: 'Are you sure,you want to delte the account and its articles ?' }%>
                                <%end%>
                            <%end%>
                        </div>
                        <div class="card-footer text-muted">
                            <small>Joined <%=time_ago_in_words(user.created_at)%> ago</small>
                        </div>
                    </div> 
                </div>
            </div>  
        <%end%>
    </div>
    <div class="apple_pagination">
        <%= will_paginate @articles,:container=>false %>
    </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
    <%= render 'form'%>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%=@user.name%>'s Profile</h1>
<%=gravatar_for @user,200%>
<div class="text-center mt-4">
    <%if logged_in? && @user==current_user%>
        <%=link_to "Edit Your Profile",edit_user_path,class:"btn btn-outline-info"%>
    <%end%>
</div>
<h3 class="text-center mt-4"><%=@user.name%> Articles</h3> 
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>
<%= render'articles/article'%>
<div class="apple_pagination">
    <%= will_paginate @articles,:container=>false %>
</div>